//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaStall_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeaInventory
    {
        public int Sr_no { get; set; }
        public string TeaName { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
    }
}
